In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
# Входные данные:
# Reshape необходим, чтобы преобразовать одномерный массив в двумерный,
# где каждый элемент находится в своей строке
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [4]:
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [7]:
model = LinearRegression()
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
# Чем выше R2, тем лучше. Минимум - 0.5. Идеально - 1
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [9]:
# y = b0 + b1 * x
print('intercept:', model.intercept_)  # b0
print('slope:', model.coef_)  # b1

intercept: 5.633333333333329
slope: [0.54]


In [12]:
# Если Y превратить в двумерный массив (с помощью rashape),
# то значения коэффициентов останутся прежними, но поменяется структура вывода
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))
print('intercept:', new_model.intercept_)
print('slope:', new_model.coef_)

intercept: [5.63333333]
slope: [[0.54]]


In [13]:
# Делаем предсказания по известным данным
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [14]:
# Предсказания, через формулу прямой линии
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [15]:
# Тоже самое, но вывод одномерный.
# Для этого надо подать одномерный X
y_pred = model.intercept_ + model.coef_ * x.flatten()
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
# Генерим новый X для предсказаний (новые данные)
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [18]:
# Собственно предсказания
y_new = model.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]


Источник:

https://proglib.io/p/linear-regression